
.ifndef CORE_INC
.define CORE_INC
;-------------------------------------------------------------------------------

.globalzp r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15
.globalzp i0, i1, i2, i3, i4, i5, i6, i7
.globalzp n0, n1, n2, n3, n4, n5, n6, n7

.global nmi, reset, irq

;-------------------------------------------------------------------------------
.endif ;CORE_INC

